### ISSUE TITLE
RB Vogui with UR10 Arm Not Working

### ISSUE THREAD

**Issue by JamesKeegan1** [RobotnikAutomation/rbvogui_sim#1]
![Screenshot of Error](https://user-images.githubusercontent.com/68841450/133464430-025bb942-e1ef-4712-8f80-1053d85af5b9.png)

Hi RB Vogui Team,

I am consistently running into this error when trying to run the command to bring up the RBVogui with a UR10 attached to the top. I was wondering if you could give me some assistance in fixing this error as physical testing should begin soon and I need to have my simulation working effectively before this.

Kind regards
James Keegan

**Comment by robert-ros** [comment]
Hi James! 

Yesterday I updated this repository according to the other repositories.

Follow the readme again (because I've update some dependencies and spawn commands). 

In order to avoid other problems, I recommend you delete your local workspace and create it again. In addition, use the melodic-devel branch.

**Comment by robert-ros** [comment]
Hi James!

Were you able to start the robot in the simulation?

**Comment by robert-ros** [comment]
I close this issue because it was resolved via email.

In short, please don't forget to install the dependencies

```
rosdep install --from-paths src --ignore-src -y
```
